version: "2"
services:
  memcached:
    image: memcached
    ports:
      - "11211:11211"
  db:
    image: postgres:11
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5433:5432"
  redis:
    image: redis
    ports:
      - "6379:6379"
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "2025:1025"
      - "1080:1080"
