default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("RAILS_DATABASE_HOST") { 'localhost' } %>
  username: postgres
  password:
  port: 5433

development:
  <<: *default
  database: wallets_development

test: &test
  <<: *default
  database: wallets_test
